# Generated by Django 2.2.3 on 2019-07-26 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 26, 20, 51, 50, 944648), verbose_name='Date published'),
        ),
    ]
