# Generated by Django 2.2.3 on 2019-07-27 02:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190726_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 27, 4, 26, 16, 106853), verbose_name='Date published'),
        ),
    ]
