# Generated by Django 2.2.3 on 2019-08-14 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190813_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 14, 18, 42, 48, 154500), verbose_name='Date published'),
        ),
    ]
