# Generated by Django 2.2.3 on 2019-08-15 19:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190814_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_course', models.CharField(max_length=200)),
                ('course_summary', models.CharField(max_length=200)),
                ('tutorial_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.TutorialCategory', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='tutorial_series',
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 15, 21, 12, 3, 77728), verbose_name='Date published'),
        ),
        migrations.DeleteModel(
            name='TutorialSeries',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='tutorial_course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.TutorialCourse', verbose_name='Courses'),
        ),
    ]
