# Generated by Django 2.2.3 on 2019-08-05 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
