# Generated by Django 2.2.3 on 2019-08-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='model_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
